# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: example.com
    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs below for complete description
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: orderer
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Artist
  # ---------------------------------------------------------------------------
  - Name: Artist
    Domain: artist.example.com
    Template: # Peer 수
      Count: 1
    Users: # User 수
      Count: 1
  # ---------------------------------------------------------------------------
  # Company
  # ---------------------------------------------------------------------------
  - Name: Company
    Domain: company.example.com
    Template:
      Count: 1
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
  # Client
  # ---------------------------------------------------------------------------
  - Name: Client
    Domain: client.example.com
    Template:
      Count: 1
    Users:
      Count: 1